#!/usr/bin/env bash

STAGED=$(git diff --cached --name-only --diff-filter=ACM)

STAGED_SH=$(echo STAGED) | grep -v Makefile # shfmt removes makefile indents for some reason.

echo "$STAGED_SH" | xargs shfmt -w
echo "$STAGED" | xargs git add
